# Generated by Django 4.0.5 on 2023-09-03 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_pwd', models.CharField(max_length=255)),
                ('user_nickname', models.CharField(max_length=255, null=True)),
                ('user_cover', models.CharField(max_length=255, null=True)),
                ('user_sex', models.CharField(max_length=4, null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_Mobile', models.CharField(max_length=16, null=True)),
                ('user_address', models.CharField(max_length=255, null=True)),
                ('user_sign_time', models.CharField(max_length=50)),
                ('user_last_login', models.CharField(max_length=255, null=True)),
                ('user_lv', models.IntegerField(default=1)),
                ('user_lv_msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nas.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonlyCode', models.CharField(max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nas.users_table')),
            ],
        ),
    ]
