# Generated by Django 4.0.5 on 2023-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='user_Disk',
            field=models.CharField(default=123456, max_length=40),
            preserve_default=False,
        ),
    ]
