# Generated by Django 4.0.5 on 2023-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0004_users_table_user_download_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='user_QBdownload_List',
            field=models.TextField(null=True),
        ),
    ]
